backend:
  - changed-files:
    - any-glob-to-any-file: 'backend/**/*'

frontend:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**/*'

documentation:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', 'docs/**/*']

dependencies:
  - changed-files:
    - any-glob-to-any-file: ['**/package.json', '**/package-lock.json']

ci-cd:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'

configuration:
  - changed-files:
    - any-glob-to-any-file: ['**/*.config.js', '**/*.config.ts', '**/.*rc', '**/.*.yml', '**/.*.yaml']
